### ISSUE TITLE
Incorrect Java version Forge

### ISSUE THREAD

**Issue by Larsdeijsbeer** [wisp-gg/images#3]
It doesn't detect the correct Java version for Forge 1.18.2.
![unknown](https://user-images.githubusercontent.com/27996312/163680817-e497c436-c270-430c-928a-08c3606ae23d.png)
The version should be Java 17 instead of Java 16.

**Comment by TrixterTheTux** [comment]
Should be now fixed. Note that you'll have to download the version again from the version installer for the fix to apply.
